### ISSUE TITLE
[Catalog] DerivedCustomResourceDefinition Controller

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#134]
`DerivedCustomResourceDefinition` is deriving a new CRD from a given one.

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: DerivedCustomResourceDefinition
metadata:
  name: couchdbs.eu-west-1
  namespace: provider-example-cloud
spec:
  baseCRD:
    name: couchdbinternal.eu-west-1.example.cloud

  kindOverride: CouchDB

  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
status:
  phase: Ready
  conditions: []
  observedGeneration: 10
```

The derived CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    # Provider name
    kubecarrier.io/provider: example.cloud
    # ServiceCluster name
    kubecarrier.io/service-cluster: eu-west-1

  # name is singular kind + "." + group
  name: couchdb.eu-west-1.example.cloud
spec:
  # group is ServiceCluster Name + "." + Provider Name
  group: eu-west-1.example.cloud
  names:
    # uses CRDDiscovery.spec.kindOverride and generates listKind/plural/singular as in:
    # https://github.com/kubernetes-sigs/controller-tools/blob/v0.2.4/pkg/crd/spec.go#L58
    kind: CouchDB
    listKind: CouchDBList
    plural: couchdbs
    singular: couchdb
status: {}
```
