### ISSUE TITLE
[Catalog v2] DerivedCR is created/managed by CatalogEntry.

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubecarrier#192]
Merge the `DerivedCR` with `CatalogEntry` (still call it `CatalogEntry`).

**Example**
```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: CatalogEntry
metadata:
  name: couchdb.eu-west-1
  namespace: <provider>
spec:
  baseCRD:
    name: couchdbinternals.eu-west-1.provider
  metadata:
    displayName: test
    description: ''
  
  # optional?
  derive:
    kindOverride: CouchDB
    expose:
    - '...'
```
