### ISSUE TITLE
Simplify ServiceCluster API

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#212]
Rename `ServiceClusterRegistration` into `Ferry` and start a `Ferry` instance when a new `ServiceCluster` object is created.

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: ServiceCluster
metadata:
  name: us-east-1
spec:
  metadata:
    displayName: US East 1
    description: ''
  kubeconfigSecret:
    name: us-east-1-kubeconfig
---
apiVersion: operator.kubecarrier.io/v1alpha1
kind: Ferry
metadata:
  name: us-east-1
spec:
  kubeconfigSecret:
    name: us-east-1-kubeconfig
```

This aims to solve a few things:
- ATM, its not possible to create a `ServiceClusterRegistration` object with metadata set.  
  This requires a user to first create the `ServiceClusterRegistration` object and then edit the `ServiceCluster` object that is automatically created.

- `ServiceCluster` objects are not cleaned up when a `ServiceClusterRegistration` object is deleted
