### ISSUE TITLE
ServiceClusterAssignment v2

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#220]
`ServiceClusterAssignment` objects are being created implicitly when the first CRD of a `ServiceCluster` is created in a Namespace on the master cluster.
Currently we have no solution for cleaning them up again.

Creating these `ServiceClusterAssignment` objects lazy also creates issues with the upcoming catapult webhook implementation.
Because we don't know the target Namespace in the ServiceCluster, before the object has been created, we cannot validate against the right Namespace in the ServiceCluster.

---

To solve these issues, we will tie the livecycle of `ServiceClusterAssignment` object to Namespaces in the master cluster instead of individual service instances.

Adding a `kubecarrier.io/assignment/<provider>.<service-cluster>` label to a `Namespace` will automatically create (if not already present) a `ServiceClusterAssignment`.

```yaml
kind: Namespace
metadata:
  name: some-namespace
  labels:
    kubecarrier.io/assignment/<provider>.<service-cluster>: 'true'
spec: {}
---
kind: ServiceClusterAssignment
metadata:
  name: some-namespace.<service-cluster>
  namespace: <management-namespace>
spec:
  masterNamespace:
    name: some-namespace
  serviceCluster:
    name: <service-cluster>
```

Removing the `kubecarrier.io/assignment/<provider>.<service-cluster>` label or deleting the Namespace will automatically delete the `ServiceClusterAssignment` as well.

---

To help administrators find the right `ServiceClusterAssignment` and service cluster `Namespace` for each namespace on the master cluster, we should add a few labels and automatically propagate some labels to each object.
Because just propagating and overriding all labels, breaks existing workflows, we will just touch labels with a prefix of `kubecarrier.io/`.
The `kubecarrier.io/assignment/*` label is excluded, as it's not adding information to the `ServiceClusterAssignment` or service cluster `Namespace`.

```yaml
kind: Namespace
metadata:
  name: some-namespace
  labels:
    kubecarrier.io/assignment/<provider>.<service-cluster>: 'true'
    kubecarrier.io/*: 'something'
spec: {}
---
kind: ServiceClusterAssignment
metadata:
  name: some-namespace.<service-cluster>
  namespace: <management-namespace>
  labels:
    kubecarrier.io/*: 'something'
---
kind: Namespace
metadata:
  name: some-namespace
  labels:
    kubecarrier.io/*: 'something'
spec: {}
```
