### ISSUE TITLE
Catapult Cross-Cluster Validation/Mutation Webhooks

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#221]
Operators may implement Validation and Mutation webhooks for their CRDs and we want to reuse them across clusters, to ensure that the CRD instances are valid and defaults are applied.

## Dynamic Webhook for arbitrary CRD support - Jiachengs proposal:

In KubeCarrier, the main feature is to provide services by working with arbitrary CRDs. Provider can config
the fields that can be exposed to the Tenant by creating the `DerivedCustomResourceDefinition` object. Then the
Tenant can create objects based on it.

In some cases, not all the mandatory fields are exposed to the Tenant within the `DerivedCustomResourceDefinition`.
in this scenario, it is very important to have mutating/validating webhooks to perform necessary
defaulting for the non-exposed fields and validating for Tenant configurable fields.

### Mutating/Validating Webhooks
Mutating/Validating webhooks are supported by performing a dry-run operation (create/update) against the kube-apiserver, specifically, webhooks will be deployed by catapult and elevator components:
- elevator: performs dry-run operation to against master cluster kube-apiserver (webhooks of Provider-wise CRD (InternalCRD))
- catapult: performs dry-run operation to against service cluster kube-apiserver (webhooks of the baseCRD in the CustomResourceDefinitionDiscovery)

#### Request Flow
Tenant creates `couchdbexternals.eu-west-1.example.cloud`
-> master cluster kube-apiserver webhooks
-> dry-run against Internal CRD `CouchdbInternal` webhooks
-> service cluster kube-apiserver webhooks
-> dry-run against Internal CRD `Couchdb` webhooks

---

For this to work, some additional considerations need to be made:

1. `ServiceClusterAssignment` object for your Namespace needs to be created and be Ready BEFORE the webhook is called.
2. If no `ServiceClusterAssignment` object is available for the current Namespace, creates and updates should be denied.
3. Instead of handle validation of update/create requests according to the `req.Operation`, webhook handles that by checking the occurrence of the `ServiceClusterObj`, which means:
    - If the `ServiceClusterObj` is found, the webhook regards this request as update request, and do dry-run update.
    - If the `ServiceClusterObj` is not found, the webhook regards this request as create request, and do dry-run create.
4. Webhooks increase the complexity of the system considerably and makes the Master Cluster partly depending on the state of the ServiceCluster, so we want to make it configurable.

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: CustomResourceDiscoverySet
metadata:
  name: couchdb
spec:
  crd:
    name: couchdbs.couchdb.io
  serviceClusterSelector: {}
  # New Field
  webhookStrategy: None
---
apiVersion: kubecarrier.io/v1alpha1
kind: CustomResourceDiscovery
metadata:
  name: couchdb.eu-west-1
spec:
  crd:
    name: couchdbs.couchdb.io
  serviceCluster:
    name: eu-west-1
  # New Field
  webhookStrategy: None
  # None (default) -> will only use a webhook for consideration 2.
  # ServiceCluster -> will call the webhooks in the ServiceCluster
```

---

Possible future extensions:
- Add the ability to specify in-master-cluster services as webhook endpoint

Ref: #220
