### ISSUE TITLE
[Bug] Provider should not be it's own Tenant

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#261]
**Describe the bug**
When creating a `Account` like:
```
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: Account
metadata:
  name: team-a
spec:
  metadata:
    displayName: The A Team
    description: In 1972, a crack commando unit was sent to prison by a military court...
  roles:
  - Provider
  - Tenant
```

The Provider will find himself has a available Tenant:
```
$ kubectl get -n team-a tenantreference
NAME     AGE
team-a   30s
```

This might result in config loops or other catastrophes.

**To Reproduce**
See above

**Expected behavior**
The `Provider` will not see himself as a `TenantReference`.
