### ISSUE TITLE
Use Kubernetes common/recommended labels

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#278]
Apply Kubernetes common or recommended labels to Operator-managed objects.

| Key | Description |	Example |	Type |
| - | - | - | - |
| app.kubernetes.io/name | The name of the application | mysql | string |
| app.kubernetes.io/instance | A unique name identifying the instance of an application |	wordpress-abcxzy | string |
| app.kubernetes.io/version | The current version of the application (e.g., a semantic version, revision hash, etc.) | 5.7.21 | string |
| app.kubernetes.io/component | The component within the architecture |	database	| string |
| app.kubernetes.io/part-of |	The name of a higher level application this one is part of |	wordpress |	string |
| app.kubernetes.io/managed-by | The tool being used to manage the operation of an application | helm | string |

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

## Benefits

- Allows to discover dependencies/all objects belonging to a `Ferry`/`Catapult`/`Elevator`/`KubeCarrier` instance
- Allows to easily see the deployed version

## Examples

**Ferry**

```yaml
metadata:
  labels:
    app.kubernetes.io/name: ferry
    app.kubernetes.io/instance: eu-west-1
    app.kubernetes.io/version: v0.1.0
    app.kubernetes.io/managed-by: kubecarrier-operator
```

**Catapult**

```yaml
metadata:
  labels:
    app.kubernetes.io/name: catapult
    app.kubernetes.io/instance: redisinternals.eu-west-1.team-a
    app.kubernetes.io/version: v0.1.0
    app.kubernetes.io/managed-by: kubecarrier-operator
```
