### ISSUE TITLE
[Catalog Enhancement] Provider can set fields which are not exposed to the Tenant

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubecarrier#294]
# Motivation and Introduction
Currently, in our catalog model, the provider can specify which fields he/she wants to expose to tenants, and configured by tenants. This can be done by specifying the `Expose` field in the `DerivedCustomReosurce`'s `Spec`. 
(In the following, for simplifying the discussion, we call the baseCRD of the `DerivedCR` as `ProviderCRD`, and the output CRD of `DerivedCR` is `TenantCRD`, and the instances of these CRDs are `ProviderObj` and `TenantObj` respectively. )
For the current implementation, we assume that all the required fields of the `ProviderCRD` are exposed to the tenant in the `TenantCRD`, so the the `ProviderObj` can be created when the tenant creates `TenantObj`. However, there can be the case that the provider wants to default some required fields and not to expose them to tenants. With the current implementation, the `ProviderObj` can not be created from `TenantObj` since some required fields are missing and the request will be rejected by `ProviderObj` validation webhooks.
This Epic is to tackle this issue and to add the support of this feature.
# Proposed implementation
## DerivedCustomResource
Adding a `default` field in the `DerivedCustomResource.Spec`
```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: DerivedCustomResource
metadata:
  name: couchdbs.eu-west-1
  namespace: provider-example-cloud
spec:
  baseCRD:
    name: couchdbinternal.eu-west-1.example.cloud
  kindOverride: CouchDB
  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
  default:
  - versions:
    # versions of the CRD that this default config can be applied to
    - v1alpha1
    # fields that are defaulted by provider
    fields:
      .spec.image: value1
      .spec.version: value2
status:
  phase: Ready
  conditions: []
  observedGeneration: 10
```
## DerivedCustomResource Webhook
Adding a webhook for DerivedCustomResource, to ensure that:
1. Every required field in of the `baseCRD` is either being exposed to the tenant in the `expose` or being defaulted by provider in the `defaut` field.
2. All the spec fields can only present in either  `expose` or `default`, not in both of them.

## Elevator Controller and Webhook
Implement the logic of the defaulting both in the tenantobj_controller and elevator webhook, this is because:
1. Elevator webhook needs to default these fields to preform `dry-run` request.
2. Elevator controller needs to default these fields to craete `ProviderObj`.

**Comment by nmiculinic** [comment]
> However, there can be the case that the provider wants to default some required fields and not to expose them to tenants

that is not something I'd call defaulting. The provider should be able to set some fields for each created `ProviderObj`, the fields which aren't exposed to the `TenantObj`. 

The good thing is if the baseCRD is properly defined with [strategic merge path](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md), see https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md#api-topology   for proper OpenAPI annotations; We can do the following:

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: DerivedCustomResource
metadata:
  name: couchdbs.eu-west-1
  namespace: provider-example-cloud
spec:
  baseCRD:
    name: couchdbinternal.eu-west-1.example.cloud
  kindOverride: CouchDB
  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
  patch:
  - versions:
    # versions of the CRD that this default config can be applied to
    -  v1alpha1
    patch: 
      spec:
        image: couchdb-supreme
        version: v3.14
status:
  phase: Ready
  conditions: []
  observedGeneration: 10
```

Then the workflow would work something like this:

* tenant creates TenentObj
* The elevator webhook is created.
* Tenant Obj is converted to ProviderObj. Afterward, we apply defined patch on that object using the https://github.com/kubernetes-sigs/structured-merge-diff library. It would work the same as ordinary kubernetes server-side-apply. 
* ProviderObj goes through typical webhooks process, maybe modified
* TenantObj recieves the modification from ProviderObj webhooks (e.g. `.spec.prop1` could be exposed to tenantCRD, but tenant hasn't set it up, thus it defaults)
* and now finally tenentObj is created

Similar transition happens in the elevator controller for creating the ProviderObj from TenenatObjs

**Comment by aborilov** [comment]
where do we set `default` values?

why don't put `default` section under `versions`

```
expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
   default:
    # fields that are defaulted by provider
    fields:
    - jsonPath: .spec.image
    - jsonPath: .spec.version
```
