### ISSUE TITLE
[Provider Patch] Implement the Patch support for DerivceCustomResource

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubecarrier#301]
Add a `patch` field in the `DerivceCR`'s exposeconfig:
```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: DerivedCustomResource
metadata:
  name: couchdbs.eu-west-1
  namespace: provider-example-cloud
spec:
  baseCRD:
    name: couchdbinternal.eu-west-1.example.cloud
  kindOverride: CouchDB
  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
    patch:
      spec:
        image: couchdb-supreme
        version: v3.14
status:
  phase: Ready
  conditions: []
  observedGeneration: 10
```
Additionally, the patch logic should be implemented in the tenantobj_controller of `Elevator`.
