### ISSUE TITLE
Multi Region

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#325]
A main goal of KubeCarrier is the central management of applications/services across Kubernetes Clusters.
These Kubernetes Clusters may run on prem, in the cloud, on the edge and across the globe.

To enable KubeCarrier to work in globally distributed and network separated environments and to deal with growth of the system. The KubeCarrier controllers may be distributed across multiple Management clusters.

## Goals

- Enable management clusters (and their Service Clusters) behind firewalls
- Lower latency/Internet data transfer
- Shard load across multiple management clusters
- Enable "availability zones" for KubeCarrier

## Regions

KubeCarrier treats every `ServiceCluster` as a Region. Each region can have differences in object schemas and are exposed to Tenants. They are similar in scope to regions in AWS or GCP.

## RegionClaims

`RegionClaim` objects claim a region for a KubeCarrier installation and prevent the same `Region` being registered in multiple KubeCarrier `ManagementClusters`.

`RegionClaim` objects are Namespaced and belong to Providers.

`ServiceCluster` objects are stuck in a `Pending` state until their `RegionClaim` could is bound and thus acknowledged by the central `KubeCarrier` installation.

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: RegionClaim
metadata:
  name: eu-west-1
  namespace: loodse
spec: {}
status:
  phase: Bound
  observedGeneration: 0
---
apiVersion: kubecarrier.io/v1alpha1
kind: RegionClaim
metadata:
  name: us-east-1
  namespace: loodse
spec: {}
status:
  phase: Conflict
  observedGeneration: 0
```

## ManagementClusters

ManagementClusters are KubeCarrier installations that are deployed in another region. Multiple ManagementClusters can be controlled from a single "Master" and the KubeCarrier API will provide access to all ManagementClusters.

Each `ManagementCluster` is responsible for a set of Regions the existence of multiple ManagementClusters is hidden from Tenants. Providers can spread management of their Services across multiple `ManagementClusters` for resiliency and because of network considerations (Latency, Firewalls, etc) e.g. We don't want to manage Services in Japan from a KubeCarrier installation in Germany.

`ManagementCluster` objects configures access to other `KubeCarrier` installations for multi region deployments.
A default `local` ManagementCluster will be always present with a `KubeCarrier` installation thats set to `master=true`.

`ManagementCluster` objects are Cluster-Scoped.

```yaml
apiVersion: master.kubecarrier.io/v1alpha1
kind: ManagementCluster
metadata:
  name: local
spec: {}
status:
  phase: Ready
  conditions: []
  observedGeneration: 0
  regions: []
  kubeCarrierVersion:
    version: v0.2.0
    #...
---
apiVersion: master.kubecarrier.io/v1alpha1
kind: ManagementCluster
metadata:
  name: eu-west
spec:
  kubeconfigSecret:
    name: eu-west-kubeconfig
status:
  phase: Ready
  conditions: []
  observedGeneration: 0
  regions:
  - name: eu-west-1
    provider: loodse
  - name: eu-west-2
    provider: loodse
  - name: eu-west-1
    provider: not-loodse
---
apiVersion: master.kubecarrier.io/v1alpha1
kind: ManagementCluster
metadata:
  name: us-east
spec:
  kubeconfigSecret:
    name: us-east-kubeconfig
status:
  phase: Ready
  conditions: []
  observedGeneration: 0
  regions:
  - name: us-east-1
    provider: loodse
  - name: us-east-1
    provider: not-loodse
```

The `KubeCarrier` object will be extended with a new `master` flag (default False) that will trigger the deployment of the KubeCarrier API server and Multi-Region controllers.

```yaml
apiVersion: operator.kubecarrier.io/v1alpha1
kind: KubeCarrier
metadata:
  name: kubecarrier
spec:
  master: true
```

KubeCarrier installations with the `master` flag set to true, cannot be registered as a `ManagementCluster`.

## Account Management

`Accounts` should me managed in the central Master KubeCarrier installation and are reconciled into all `ManagementClusters`. `Accounts` in the master cluster will report additional conditions about the state of this reconciliation into multiple `ManagementClusters`. `Accounts` in the master cluster are considered `Unready` when the Account is not present in all `ManagementClusters`.
