### ISSUE TITLE
Operator Paused Flags

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#343]
Allow to pause reconcilation of operator managed instances.
This feature is intended for debugging and troubleshooting in KubeCarrier installations.

Acceptance Criteria:
- Managing Controllers (DerivedCR/ServiceCluster/etc) MUST not change the pause flag/MUST not change it back to `paused: false`
- Controllers MUST skip reconciling objects with `paused: true`
- Controllers MUST still update the status
- Controllers MUST assume the component is in Ready state
- Controllers SHOULD report the object to be paused

Example Fields:

```yaml
spec:
  paused: true
status:
  conditions:
  - type: Paused
    status: "True"
    message: "Reconcilation is paused"
    reason: Paused
  - type: Ready
    status: "True"
    message: "Reconcilation is paused, assuming component is ready."
    reason: Paused
  phase: Paused
```
