### ISSUE TITLE
Tower - Local ManagementCluster

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#344]
`Peer` objects are cluster-scoped and track management clusters that are part of this multi-region deployment.

See the Epic for further details.

This task should add support to specify the current/local cluster as a `Peer`.

Acceptance Criteria:
- API group `master.kubecarrier.io` exists
- `ManagementCluster.master.kubecarrier.io` type exists
- the `local` Peer is always reported as ready

Example:

```yaml
apiVersion: master.kubecarrier.io/v1alpha1
kind: ManagementCluster
metadata:
  name: local
spec: {}
status:
  phase: Ready
  conditions: []
  observedGeneration: 0
```
