### ISSUE TITLE
Tower - RegionClaims

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#346]
`RegionClaim` objects ensure that the same `Region` can only exist in a single management cluster, so it can be used to route API server requests to the right management cluster.

Acceptance Criteria:
- `RegionClaim.kubecarrier.io` type exists
- `Bound` RegionClaims are reported on their `Peer`
- A `RegionClaim` with the same name and provider may only be `Bound` once across all `Peers`
- multiple `RegionClaims` with the same name but DIFFERENT providers can be `Bound`
- `RegionCleims` MAY be reconciled within the `PeerController`, even if that means they are only reconciled every `peerHealthcheckPeriod`

Example `RegionClaim`:

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: RegionClaim
metadata:
  name: eu-west-1
  namespace: loodse
spec: {}
status:
  phase: Bound
  observedGeneration: 0
---
apiVersion: kubecarrier.io/v1alpha1
kind: RegionClaim
metadata:
  name: us-east-1
  namespace: loodse
spec: {}
status:
  phase: Conflict
  observedGeneration: 0
```

Example `Peer` object:

```yaml
apiVersion: master.kubecarrier.io/v1alpha1
kind: Peer
metadata:
  name: eu-west
spec:
  kubeconfigSecret:
    name: eu-west-kubeconfig
status:
  phase: Ready
  conditions: []
  observedGeneration: 0
  regions:
  - name: eu-west-1
    provider: loodse
  - name: eu-west-2
    provider: loodse
  - name: eu-west-1
    provider: not-loodse
```
