### ISSUE TITLE
API Static User Configuration

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#447]
When installing KubeCarrier the KubeCarrier API server requires an OIDC setup to allow user logins and thus the UI to work.

Requiring an OIDC installation is a big hurdle to try out KubeCarrier. To ease in this initial installation, we should support static user credentials.

**Example Configuration**

```yaml
apiVersion: operator.kubecarrier.io/v1alpha1
kind: KubeCarrier
metadata:
  name: kubecarrier
spec:
  api:
    staticUsers:
      htpasswdSecret:
        name: kubecarrier-users
```

**Acceptance Criteria**
- allows to configure a `.htpasswd` file to be referenced for static users
