### ISSUE TITLE
API Server CRD auth schema

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/kubecarrier#470]
https://github.com/kubermatic/kubecarrier/pull/460#discussion_r439323997

As continued from this comment here's my proposed API Server CRD schema for authentication:

```yaml
authentication:
- oidc: {...}
- anonymous: {enabled: true} 
```

the list ordering would carry over in the authentication-mode ordering in the API server CLI flag, and finally how the authentication providers shall be evaluated.

**Comment by aborilov** [comment]
@nmiculinic 
in that case, what is the type of the map values? we need to have concrete types for `oidc` configuration, so we can validate it.
```
authentication:
- oidc: {...}
- anonymous: {enabled: true} 
```

what about if we just add `Order` list
```
authentication:
 - oidc: {optional oidc config here}
 - staticUsers: {optional staticUsers config}
 - order:
  - oidc
  - statisUsers
  - token
  - anonymous
```
