### ISSUE TITLE
[Documentation] Operators need to use Namespaced CRD and watch whole cluster

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#548]
Operators that can be connected to KubeCarrier, need to have a namespaced API (Namespace Scoped CRDs) and need to watch the whole cluster to create/operate their applications in.

KubeCarrier requires this limitation, as it's isolating users into separated namespaces.

This issue is about adding this to our documentation.

**Comment by aborilov** [comment]
most of the operators using https://sdk.operatorframework.io/ and to make the watch for the whole cluster we need to set `WATCH_NAMESPACE` env to an empty string(which means the whole cluster)
https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-cluster-scoped-operators-with-multinamespacedcachebuilder.

but a lot of the operators setting this value to
```
env:
      - name: WATCH_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace 
```
>NOTE WATCH_NAMESPACE here will always be set as the namespace where the operator is deployed.
