### ISSUE TITLE
[Federation] CustomResourceDefinitionConfig

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#62]
`CustomResourceDefinitionConfig` holds options to derive CRD's within KubeCarrier.

**Acceptance Criteria**
- configuration is using JSON Paths `test.field.something`
- Internal CRD should be prefixed with `Internal` e.g. `InternalCouchDB`
- the API group is composed of the service cluster name
- `crdc` is setup as shorthand

**Example**
```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: CustomResourceDefinitionConfig
metadata:
  name: couchdbs.eu-west-1
spec:
  # configures the CustomResourceDefinitionDiscovery instance
  crd:
    name: couchdbs.couchdb.io
  serviceCluster:
    name: eu-west-1

  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
```
