### ISSUE TITLE
[Federation] CustomResourceDefinitionConfigSet

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#63]
`CustomResourceDefinitionConfigSet` manages `CustomResourceDefinitionConfig` instances for multiple ServiceClusters.

**Acceptance Criteria**
- `crdcs` is setup as shorthand

**Example**
```yaml
apiVersion: core.kubecarrier.io/v1alpha1
kind: CustomResourceDefinitionConfigSet
metadata:
  name: couchdbs
spec:
  # configures the CustomResourceDefinitionDiscovery instance
  crd:
    name: couchdbs.couchdb.io
  serviceClusterSelector: {}

  expose:
  - versions:
    # versions of the CRD that this expose config can be applied to
    - v1alpha1
    # fields that are exposed on the external/public instance
    fields:
    - jsonPath: .spec.username
    - jsonPath: .spec.password
    - jsonPath: .status.address
    - jsonPath: .status.fauxtonAddress
    - jsonPath: .status.observedGeneration
    - jsonPath: .status.phase
```
