### ISSUE TITLE
[Federation] Catapult Cross-Cluster Reconciler

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#64]
Implement cross-cluster reconcilation for CRD instances.

**Example CRD**

```yaml
apiVersion: operator.kubecarrier.io/v1alpha1
kind: Catapult
metadata:
  name: couchdbs.eu-west-1
  namespace: provider-example-cloud
spec:
  internalCRD:
    # from CRDDiscovery status
    # generated from ServiceCluster
    kind: CouchDBInternal
    version: v1alpha1
    group: eu-west-1.example.cloud

  serviceClusterCRD:
    # from CRDDiscovery status
    kind: CouchDB
    version: v1alpha1
    group: couchdb.couchdb.io

  externalCRD: # optional
    # from CRDConfig status
    kind: CouchDB
    version: v1alpha1
    group: eu-west-1.example.cloud

status:
  phase: Ready
  conditions: []
  observedGeneration: 10
```
