### ISSUE TITLE
[Catalog] CatalogEntry

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#72]
The `CatalogEntry` object adds additional metadata to a set of CRD's and groups the same Kind for multiple `ServiceClusters`, they are configured by a provider in it's namespace.

**Acceptance Criteria**
- [x] A `CRD` can only be referenced by a single `CatalogEntry` -> Check with a annotation
- [x] `kubecarrier.io/provider` selector is added by default, depending on the provider namespace that the `CatalogEntry` is created into.

**Example**

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: CatalogEntry
metadata:
  name: couchdbs
spec:
  # must be specified, matches NONE by default
  crdSelector:
    matchLabels:
      # automatic system label (Name of CustomResourceDefinitionConfigSet)
      # name TBD
      kubecarrier.io/crdcs: couchdbs

      # this selector is hardcoded and always added by the controller,
      # when searching for CRD's to prevent privilege escalation
      kubecarrier.io/provider: example.cloud

  # metadata that describes this service
  metadata:
    displayName: Couch DB
    description: The comfy nosql database.

status:
  crds:
  - name: couchdbs.eu-west-1.example.cloud
    kind: CouchDB
    group: eu-west-1.example.cloud
    # can be discovered from CRD annotation or label "kubecarrier.io/service-cluster"
    serviceCluster: eu-west-1
    versions:
    - name: v1alpha1
      schema: {}
  - name: couchdbs.us-east-1.example.cloud
    kind: CouchDB
    group: us-east-1.example.cloud
    # can be discovered from CRD annotation or label "kubecarrier.io/service-cluster"
    serviceCluster: us-east-1
    - name: v1alpha1
      schema: {}
```
