### ISSUE TITLE
[Catalog] Catalog

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#73]
`Catalog` objects are configure the offering of a set of services (`CatalogEntries` #72  ) to a set of user groups `Tenant(References)` #30 .

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: Catalog
metadata:
  name: default
spec:
  # matches no CatalogEntries, if not specified
  catalogEntrySelector: {}

  # matches no TenantReferences, if not specified
  tenantReferenceSelector: {}

status:
  tenants:
  - name: tenant-a
  - name: tenant-b
  entries:
  - name: couchdb
```

**Acceptance Criteria**
- [x] If the CatalogEntry/TenantReference Selector is not specified(`nil`), it should match no CatalogEntries/TenatnReference.
