### ISSUE TITLE
[Catalog] ProviderReference

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#75]
`ProviderReference` objects expose additional metadata about a `Provider` to `Tenants`.

**Acceptance Criteria**
- `ProviderReference` objects should only be created for `Tenants` that have at least one `CatalogEntry/Offering` of this `Provider`.

**Example**

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: ProviderReference
metadata:
  name: example.cloud
provider:
  metadata:
    displayName: Example Cloud
    description: Cloud like it's 1990.
```
