### ISSUE TITLE
[Catalog] ServiceClusterReference

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#76]
`ServiceClusterReference` objects expose additional metadata about a `ServiceCluster` to `Tenants`.

**Acceptance Criteria**
- `ServiceClusterReference` objects should only be created for `Tenant` that have at least one `CatalogEntry/Offering` for this `ServiceCluster`.

**Example**

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: ServiceClusterReference
metadata:
  name: eu-west-1
serviceCluster:
  metadata:
    displayName: EU West 1
    description: It's in the EU, and in the west!
  provider: example.cloud
```
