### ISSUE TITLE
[Catalog] Offering

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#77]
`Offering` objects allow a `Tenant` to discover services that have been made available to him.

**Example**

```yaml
apiVersion: catalog.kubecarrier.io/v1alpha1
kind: Offering
metadata:
  name: couchdb
offering:
  metadata:
    displayName: Couch DB
    description: The comfy nosql database.

  providerReference:
    name: example.cloud

  # 1:1 from CatalogEntry status
  crds:
  - name: couchdbs.eu-west-1.example.cloud
    kind: CouchDB
    group: eu-west-1.example.cloud
    # can be discovered from CRD annotation or label "kubecarrier.io/service-cluster"
    serviceCluster: eu-west-1
    versions:
    - name: v1alpha1
      schema: {}
  - name: couchdbs.us-east-1.example.cloud
    kind: CouchDB
    group: us-east-1.example.cloud
    # can be discovered from CRD annotation or label "kubecarrier.io/service-cluster"
    serviceCluster: us-east-1
    - name: v1alpha1
      schema: {}
```
