### ISSUE TITLE
[Federation] ServiceClusterAssignment

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#89]
A `ServiceClusterAssignment` object represents a scheduling/assignment target for instances of CRDs that are managed by KubeCarrier.

**Acceptance Criteria**
- Target Namespace name is generated
- RBAC `Role/ClusterRole` is seperated for the ServiceCluster
- Is ready when the target namespace on the ServiceCluster exists

**Example**

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: ServiceClusterAssignment
metadata:
  name: default
spec:
  serviceCluster:
    name: eu-west-1

status:
  # generated namespace name on the ServiceCluster
  namespaceName: default-xxx
  conditions: []
  observedGeneration: 0
  phase: Ready
```
