### ISSUE TITLE
[Federation] Report ServiceCluster status

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubecarrier#90]
The Tender should post heartbeats and reports it's status while running.
(Prerequisite for #59)

```yaml
apiVersion: kubecarrier.io/v1alpha1
kind: ServiceCluster
metadata:
  name: eu-west-1
spec: {}

status:
  conditions: []
  observedGeneration: 0
  phase: Ready
```
